- name: Deploy authmat + dockeep infra with Docker Compose
  hosts: targets  # Matches the group in inventory.ini
  become: yes  # Use sudo for tasks requiring elevated privileges (e.g., installing packages, Docker)
  vars_files:
    - group_vars/shared_secrets.yml
    - group_vars/authmat_secrets.yml
    - group_vars/dockeep_secrets.yml
  vars:
    deployment_dir: /opt/deployment  # Directory on target host for repo clones
    infra_repo_url: https://github.com/Yohannes09/Infrastructure
    infra_repo_dir: "{{ deployment_dir }}/infra"
    authmat_repo_url: https://github.com/Yohannes09/AuthMat
    authmat_repo_dir: "{{ deployment_dir }}/auth"
    dockeep_repo_url: https://github.com/Yohannes09/DocKeep
    dockeep_repo_dir: "{{ deployment_dir }}/doc"
    repo_branch: main
    kafka_bootstrap_server: kafka:9092
    redis_host: redis
    redis_port: 6379


  tasks:
    - name: Install Docker, Compose, and Git
      apt:
        name:
          - docker.io
          - docker-compose-v2
          - git
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'


    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes
      when: ansible_os_family != 'Darwin'


    - name: Create deployment directory
      file:
        path: "{{ deployment_dir }}"
        state: directory
        mode: '0755'


    - name: Clone infra repo
      git:
        repo: "{{ infra_repo_url }}"
        dest: "{{ infra_repo_dir }}"
        version: "{{ repo_branch }}"
        force: yes
        accept_hostkey: yes
      register: infra_clone


    - name: Clone authmat repo
      git:
        repo: "{{ authmat_repo_url }}"
        dest: "{{ authmat_repo_dir }}"
        force: yes
        accept_hostkey: yes
      register: authmat_clone


    - name: Clone dockeep repo
      git:
        repo: "{{ dockeep_repo_url }}"
        dest: "{{ dockeep_repo_dir }}"
        version: "{{ repo_branch }}"
        force: yes
        accept_hostkey: yes
      register: dockeep_clone


    - name: Creating Docker app netowork
      shell: docker network create app-network


    - name: Building and containerizing Infrastructure
      shell: docker compose up -d
      args:
        chdir: "{{ infra_repo_dir }}/AuthMat-DocKeep-Infrastructure/application_infra"


    - name: Building and containerizing AuthMat
      shell: docker compose up -d
      args:
        chdir: "{{ authmat_repo_dir }}"
      environment:
        APP_PORT: 8080
        KAFKA_BOOTSTRAP_SERVERS: "{{ kafka_bootstrap_server }}"
        REDIS_HOST: "{{ redis_host }}"
        REDIS_PORT: "{{ redis_port }}"

        DB_NAME: "{{ AUTH_DB_NAME }}"
        DB_USERNAME: "{{ AUTH_DB_USERNAME }}"
        DB_PASSWORD: "{{ AUTH_DB_PASSWORD }}"
        DB_MAX_POOL_SIZE: 10
        DB_MIN_IDLE_CONNECTIONS: 5
        DB_IDLE_TIMEOUT_MS: 300000
        DB_MAX_LIFETIME_MS: 600000

        GOOGLE_OAUTH2_CLIENT_ID: "{{ GOOGLE_OAUTH2_CLIENT_ID }}"
        GOOGLE_OAUTH2_CLIENT_SECRET: "{{ GOOGLE_OAUTH2_CLIENT_SECRET }}"


    - name: Building and containerizing DocKeep
      shell: docker compose up -d
      args:
        chdir: "{{ dockeep_repo_dir }}"
      environment:
        APP_PORT: 8081
        KAFKA_BOOTSTRAP_SERVERS: "{{ kafka_bootstrap_server }}"
        REDIS_HOST: "{{ redis_host }}"
        REDIS_PORT: "{{ redis_port }}"

        DB_NAME: "{{ DOC_DB_NAME }}"
        DB_USERNAME: "{{ DOC_DB_USERNAME }}"
        DB_PASSWORD: "{{ DOC_DB_PASSWORD }}"
        DB_MAX_POOL_SIZE: 10
        DB_MIN_IDLE_CONNECTIONS: 5
        DB_IDLE_TIMEOUT_MS: 300000
        DB_MAX_LIFETIME_MS: 600000

        AWS_REGION: "{{ AWS_REGION }}"
        AWS_BUCKET_NAME: "{{ AWS_BUCKET_NAME }}"


    - name: Verify services are running
      command: docker ps
      register: docker_output
      failed_when: docker_output.rc != 0


    - name: Display running containers
      debug:
        var: docker_output.stdout_lines



# MIGHT NEED ONE DAY
#        ACCESS_TOKEN_VALIDITY_MINUTES: "{{ ACCESS_TOKEN_VALIDITY_MINUTES }}"
#        ACCESS_TOKEN_HISTORY_TRACE: "{{ ACCESS_TOKEN_HISTORY_TRACE }}"
#        ACCESS_TOKEN_KEY_SIZE: "{{ ACCESS_TOKEN_KEY_SIZE }}"
#        ACCESS_TOKEN_KEY_ALGORITHM: "{{ ACCESS_TOKEN_KEY_ALGORITHM }}"
#        ACCESS_TOKEN_JWT_ALGORITHM: "{{ ACCESS_TOKEN_JWT_ALGORITHM }}"
#        ACCESS_TOKEN_SIGNING_KEY_ROTATION_RATE_MINUTES: "{{ ACCESS_TOKEN_SIGNING_KEY_ROTATION_RATE_MINUTES }}"
#
#        REFRESH_TOKEN_VALIDITY_MINUTES: "{{ REFRESH_TOKEN_VALIDITY_MINUTES }}"
#        REFRESH_TOKEN_HISTORY_TRACE: "{{ REFRESH_TOKEN_HISTORY_TRACE }}"
#        REFRESH_TOKEN_KEY_SIZE: "{{ REFRESH_TOKEN_KEY_SIZE }}"
#        REFRESH_TOKEN_KEY_ALGORITHM: "{{ REFRESH_TOKEN_KEY_ALGORITHM }}"
#        REFRESH_TOKEN_JWT_ALGORITHM: "{{ REFRESH_TOKEN_JWT_ALGORITHM }}"
#        REFRESH_TOKEN_SIGNING_KEY_ROTATION_RATE_MINUTES: "{{ REFRESH_TOKEN_SIGNING_KEY_ROTATION_RATE_MINUTES }}"