apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authmat-db-deployment-h
spec:
  serviceName: "authmat-db-service-h"
  replicas: 1
  selector:
    matchLabels:
      app: authmat-db
  template:
    metadata:
      labels:
        app: authmat-db
    spec:
      containers:
        - name: postgres
          image: postgres:15 # SUBJECT TO CHANGE
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: authmat-db-data
              mountPath: /var/lib/postgresql/data
          env:  # Replace later, no credentials will be stored in the repo
            - name: POSTGRES_DB
              value: authmat
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: authmat-db-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password

  volumeClaimTemplates:
    - metadata:
        name: authmat-db-data # Name of the volume that will be mounted to the container
      spec:
        accessModes: [ "ReadWriteOnce" ] # Only one node in the cluster can mount this volume at a time
        resources:
          requests:
            storage: 5Gi