apiVersion: apps/v1
kind: Deployment
metadata:
  name: authmat-deployment
  labels:
    app: authmat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authmat
  template:
    metadata:
      labels:
        app: authmat
    spec:
      containers:
        - name: authmat-
          image:
          ports:
            - containerPort: 8080
          env: