apiVersion: external-secrets.oi/v1beta1
kind: ExternalSecret
metadata:
  name: authmat-secrets
  namespace: authmat
spec:
  refreshInterval: 1h
  secretsStoreRef:
    name: aws-secrets-manager
    king: ClusterSecretStore
  target:
    name: authmat-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: authmat/prod/db
        property: password