[authmat]
authmat-01 ansible_host=<EC2 IP> ansible_user=ubuntu

[dockeep]
dockeep-01 ansible_host=<EC2 IP> ansible_user=ubuntu

[services:children]
authmat
dockeep

[all:vars]
ansible_python_interpreter=/usr/bin/python3