# DOCKEEP

apiVersion: v1
kind: Service
metadata:
  name: dockeep-db-service-h
  labels:
    app: dockeep-db
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: dockeep-db