- name: Install Docker
  apt:
    name: docker.io
    state: present
  become: yes

- name: Install Docker Compose
  apt:
    name: docker-compose-plugin
    state: present
  become: yes

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enables: yes
  become: yes

- name: Ensure app-network exists
  community.docker.docker_network:
    name: app-network
    state: present

- name: Ensure monitoring-network exists
  community.docker.docker_network:
    name: monitoring-network
    state: present