apiVersion: external-secrets.io/v1beta1
kind: ClusterServiceStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: region # TODO set region
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets