on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: echo "terraform init"

      - name: Terraform Plan
        run: |
          echo " terraform plan -var="ssh_allowd_cidr=${{ secrets.SSH_ALLOWED_CIDR }}" "

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo " terraform apply -auto-approve -var="ssh_allowd_cidr=${{ secrets.SSH_ALLOWED_CIDR }}" "